language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: sH0FgQxTny8Gmjy//oNrCqoqgZvybNiTxVO/oILDvJJY0RhahKV5HCV4RgD77I8ZQ3BQzRcydBa6YLhJcPA2fEgYxV4PP+qOjmmZJgRcohM1n5sop+QA0ZDbhcHN9It+VIsNw51kkshpwI9rTRsHtc5Y7EZw8X59k9XAuFyPk+hEze7sdR0pyq2ew1uHMEqwvWn+VFjNwDgVnXv1El4tdtMVoSHfdFQSoCFbK7aqoknXOCgOlldPTtf4b23trMMFFTd6zH2o31bdtxGjfwpC76SY7Wf45AmdX/tKPITI63jd8T+i5fKFChnoRKDeIyW1YSaXAfCjP6P8W0XhHYLnw+ThGeMv08cvUJGArDj3nJGm00DToBwPMvASTr8ZRCGNPwO4iUx6452t+9oxfDEBjD/jG1xzBBTwxdZyrabxAp5AQ2tarKWAZwYtNG6IYNbXGYU0xU43bG5DkZBL0JGqv9V7pNAp5+uRBXb64iYCleo1iOpEq0BDo4xih9iCDKki4iUg46HCLwHgeURzzfxL+NTGRRA0vUYsFEz8A815DMDsvYM9h/GOdyVuLCauGkiLN8/GDeCWJ36DIzcPugOe/htMAmgn2XbWVZZwj4CHS9ojg+fgCpwnbM11KgK+1K4gHlSBwJW0XTr+gu+s1qeTKRsXOJN5MbDgZ26f3hHkuwU=
  app: protected-ocean-87186
  on:
    repo: sol-idsnake/blog-api
