language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AZi3Gv12cWiiMnN6nfglYkAtImuWAeSihsCUv5WAVqT+0bGJPREbxnqKECOGjHiz4pcVBZxTI0RF3pBvGlYf1Q6arC4yibO69T1mWTtSsTwyps2yETje4loRe/iNFXKti8AbUkrGRLFe1vWOr7cVp6sn5zwrNQOlNa4MVjyG7snFhPKDSpMi0bOoYhf7Ztxei70acwRqbJAOO+8URjFeYN9xxoe/nVM3QpkzaXVjRYoU78PjPAHSkB8VCF80ur7htKVtyfQoP9A64BgDLA53JxlvVv6QZOjmAoGXt/0uwO0MwEJuKzpDfbh5I2EFcsb0jMJuQ8xsKnXO51GGVE8puv6t++VGm4b82DMGbZbj6AR7zYBz52y+D78VEaf/EGXh0/H4vb07rDhXjvCv15iwlFgbwChWBtqLWGuP2xyQ32GJOghG4kjQ2OieCL4Id4HWD27vOSDiGAQ39GmEp1D+3Q00kvO9PlZnXtstFBKxv9iOvmJzb/ej/AWbQob0OoEeBmQJyKBBUYGKQB5WEK/+0igiC7dFREpM0RYDpNEcvr8M99irM7Gld0MpXzEtcXFlAoB5Zq9SwPKjWNLm9OOf9XcsFIr0f8Po4LiKoZOgZpmsjm+S8WESYzLl/EeR2QCdmJQE9LbTSDrJPpobBgWqL2OeqpC8Kuk/SD1q3OnKUNg=
  app: stark-springs-65341
  on:
    repo: sol-idsnake/blog-api
