language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NHd/r8iItfbNfCDKyjk1ADK2+3FrrxKQUN0CKxWOYB1Y2XzSn+RJcdryVtSnCmwrRJC1MOh3yBXELpZ7cttthUg8xgiB3o+cnZ2ojbM3zvMIl4M2rWPCveXh5IFiVOvEtwka9yVJM2lHuHxSERg4p7njz9glsYs+T+zaDbpnL52nqzObfk/D+5CICueNZpR7T1NgyrhyFdnrDCUo18cVDqYHhuGw/J9BXhdSnj5KZxR+53zNjEr7GSTWudk+LQ5PmYxFpGaCRC/u5f/rwktH+9pQwXfGn8xW1b6Zi9c4MwmWrXup96NcULj3gjy1XxPyzXt8n85xRUqgZ9tdM5jioWLEEWjtwdbDee+FkCzVUlu+OSm0sXUwQ1qD+vO0s2j3OxzguuHqKwBQoUQ9XQGZmdjLS1bR2VEZKxOeUQlRUct6t2Ctn6TKdfGUv7GowM6xMAcIWV1KMMUw3GVQpralrnYaYpfVoCwaMkLqOUiXuk/UmtmMNuL8Wit8t6OJiaJW2pxYjt5SM4qtWykObBqKt5dNYEU9XnAgukeIHuOpzEuIOwFlwFtJ27hSa3bRm6FaO2IYD1iqqRvIV69gGLl9Nm/FXwCXQ7QTmUCl4eEx69NvmnlPaTavN6YMZz3c6NIcCxwKFFIOq5apiHQwFCpFG04cXDvbl/7p13MokTT2QWo=
  app: protected-ocean-87186
  on:
    repo: sol-idsnake/blog-api
